### ISSUE TITLE
Going to /logout doesn't logout the user

### ISSUE THREAD

**Issue by bernatfortet** [VictorPeralta/supabase-remix-auth#1]
(hi @VictorPeralta this is the best starter I've found after hours of headbanging. Thank you so much!)

Issue: going directly to `/logout` will not end the session

Repro steps:
- With the code as is (no modification)
- login
- go to `/logout`

Actual behavior:
- the index show user id info

Expected behavior
- back to unauthed state where it shows `You're not logged in `

Using the logout button works fine.

**Comment by VictorPeralta** [comment]
Thanks for bringing it up, I'll look into it and update you.

**Comment by VictorPeralta** [comment]
@bernatfortet The behavior you mention should work now, any user that visits `/logout` will be logged out client and server side.
